services:
  # Frontend React App
  frontend:
    build: 
      context: ./
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge
